## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

theme = "hugo-story"

## -----------------------------------------------
## Publish
## -----------------------------------------------

title = "EverSewSlowly"
relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "https://eversewslowly.com/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

#disableKinds = ["taxonomy", "section"]
# googleAnalytics = "your-google-analytics-id"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.145.0"
  
[Params.social]
  email = "eversewslowly@gmail.com"
  instagram = "https://www.instagram.com/eversewslowly"
  pinterest = "https://www.pinterest.com/EverSewSlowly"