baseURL = "https://eversewslowly.com/"

#[Params]
#  googleAnalyticsID = "{{ getenv "GOOGLE_ANALYTICS_ID" }}

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false