baseURL = "https://eversewslowly.com/"

[Params]
  googleAnalyticsID = "G-SMHMNGCEW8"

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false