## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Ever Sew Slowly"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

#disableKinds = ["taxonomy", "section"]
# googleAnalytics = "G-XXXXXXXXXX"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Eversewslowly"
  logo = "images/refashion_mens_shirt.png"
  favicon = true

[Params.social]
  email = "eversewslowly@gmail.com"
  instagram = "https://www.instagram.com/eversewslowly"
  pinterest = "https://www.pinterest.com/EverSewSlowly"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]